from collections import OrderedDict

matches = OrderedDict(reversed(sorted({
    'bar-style': '@',
    'attributes' : "[",
    'fifths':   "]",
    'system-layout' : '+|',
    'system-margins': '~',
    'top-system-distance': '+(',
    'system-distance': "+)",
    'accidental':'J',
    'articulations': '+o',
    'actual-notes':'+}',
    'normal-notes':'+r',
    'normal-type':'+s',
    'staccato': '+%',
    'metronome':'+u',
    'direction-type': '+w',
    'attributes':'+x',
    'direction' :'+y',
    'divisions': '(',
    'dynamics':'+$',
    'top-syw-distance':'+#',
    'time-modification':'p',
    'score-partwise': ":",
    'beat-unit': '+j',
    'per-minute':'+i',
    'measure': 'I',
    'note': '}',
    'pitch':')',
    'step':'&',
    'alter':'|',
    'octave':'#',
    'duration':'W',
    'voice':'^',
    'stem': 'Z',
    'beam':'Y',
    'tie':'{',
    'transpose': '+}',
    'part': '.',
    'notations': '+l',
    'tied':'$',
    'left-margin': '+%',
    'right-margin': '+#',
    'tuplet': '+?',
    'beats': 'X',
    'beat-type': '+y',
    'syw-margins' : '+z',
    'syw-layout' : '+w',
    'kind': 'U',
    'print': 'O',
    'sign': 'M',
    'rest': 'N',
    'sound': 'Q',
    'barline': '+^',
    'line': 'P',
    'clef': 'T',
    'dot': '+v',
    '</': '!',
    '/>': 'K'
}.items(), key=lambda t: len(t[0]))))